run:
  timeout: 10m
issues:
  exclude-use-default: false
linters:
  disable:
    - maligned
    - dupl
    - gocyclo
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - structcheck
    - varcheck
    - gofmt
    - goimports
    - golint
    - ineffassign
    - typecheck
    - misspell
    - unconvert
    - whitespace
