name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.2

    - name: Install dependencies
      run: go mod tidy

    - name: Lint code
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.50.1
        args: --config .github/golangci.yml

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.2

    - name: Install dependencies
      run: go mod tidy

    - name: Build project
      run: go build ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.2

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./...

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [lint, build, test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.2

    - name: Set up GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest

    - name: Run GoReleaser
      run: goreleaser release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
